CREATE TABLE USERS (
  ID       INT                NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(50)        NOT NULL,
  PASSWORD VARCHAR(500)       NOT NULL,
  NICKNAME VARCHAR(50)
           CHARACTER SET UTF8 NOT NULL UNIQUE,
  ENABLED  BOOLEAN            NOT NULL
);

ALTER TABLE USERS DEFAULT CHARACTER SET UTF8;